### ISSUE TITLE
WiFi broken

### ISSUE THREAD

**Issue by Caio99BR** [TeamVee/VeeKernel#1]
android-msm-3.4-kk-new

**Comment by shskyinfo** [comment]
Use Wifi hack :) in module.c

**Comment by Caio99BR** [comment]
librasdioif: disagrees about version of symbol module_layout

**Comment by Caio99BR** [comment]
Possible fix https://github.com/TeamVee/VeeKernel/commit/4ca7e5230e072cdd1f909af39bfdaf88c67c9c5f

**Comment by shskyinfo** [comment]
yeah basically that

**Comment by Caio99BR** [comment]
After disable ModVersion the WiFi broken, possible cause is wlan.ko (builded by @RonGokhale) with this kernel this with the ModVersion enabled, causing this error.

**Comment by shskyinfo** [comment]
Suggest you try this https://github.com/TeamVee/SKernel_Vee/commit/085db3c2effc171aae68912f5db7dae462555203
